# Generated by Django 3.1.2 on 2020-10-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('synopsis', models.TextField(max_length=500)),
                ('pages', models.CharField(max_length=5)),
                ('year_published', models.IntegerField(max_length=7)),
                ('genre', models.CharField(max_length=30)),
                ('lccn', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(max_length=4)),
            ],
        ),
    ]
