# Generated by Django 3.1.2 on 2020-11-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201101_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('AA', 'Action and Adventures'), ('CL', 'Classics'), ('GC', 'Graphic Novels/Comic Books'), ('DM', 'Detective/Mysteries'), ('FA', 'Fantasies'), ('HF', 'Historical Fiction'), ('HR', 'Horror'), ('LF', 'Literary Fiction'), ('RO', 'Romance'), ('SF', 'Science Fiction'), ('SS', 'Short Stories'), ('ST', 'Suspense/Thrillers'), ('AB', 'Autobiographies/Biographies'), ('CO', 'Cookbooks'), ('HI', 'History'), ('PO', 'Poetry'), ('SH', 'Self-Help'), ('TC', 'True Crime')], default='Literary Fiction', max_length=2),
        ),
    ]
